// <auto-generated />
using System;
using EmployeeLibrary;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeLibrary.Migrations
{
    [DbContext(typeof(EmployeeDbContext))]
    [Migration("20250807142256_Migration2")]
    partial class Migration2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeeLibrary.Models.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3055d53d-e691-4e74-8180-26fc4189f898"),
                            Address = "123 Main St, Thoraipakkam, Chennai",
                            CreatedOn = new DateTime(2025, 8, 7, 19, 52, 55, 891, DateTimeKind.Local).AddTicks(6915),
                            Description = "Zuci Systems is a leading software development company specializing in custom software solutions, mobile app development, and web application development. We are committed to delivering high-quality software products that meet the unique needs of our clients.",
                            Email = "zucisystems@zucisystems.com",
                            IsActive = true,
                            Name = "Zuci Systems",
                            PhoneNumber = "1234567890",
                            UpdatedOn = new DateTime(2025, 8, 7, 19, 52, 55, 891, DateTimeKind.Local).AddTicks(6936)
                        });
                });

            modelBuilder.Entity("EmployeeLibrary.Models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CompanyId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CompanyId1");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9af76444-2bc7-4e01-b4cd-aa6b02b8924c"),
                            Address = "123 Sai Baba PG, Thoraipakkam, Chennai",
                            CompanyId = new Guid("3055d53d-e691-4e74-8180-26fc4189f898"),
                            CreatedOn = new DateTime(2025, 8, 7, 19, 52, 55, 891, DateTimeKind.Local).AddTicks(7202),
                            DOB = new DateTime(2003, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "bala@zucisystems.com",
                            IsActive = true,
                            Name = "Bala Venkata Rama Sai Immadisetty",
                            PhoneNumber = "9876543210",
                            Role = "Developer",
                            UpdatedOn = new DateTime(2025, 8, 7, 19, 52, 55, 891, DateTimeKind.Local).AddTicks(7203)
                        },
                        new
                        {
                            Id = new Guid("fdf99112-7e80-4185-bd3d-69e866d9400f"),
                            Address = "123 Annai Indira Nagar, Thoraipakkam, Chennai",
                            CompanyId = new Guid("3055d53d-e691-4e74-8180-26fc4189f898"),
                            CreatedOn = new DateTime(2025, 8, 7, 19, 52, 55, 891, DateTimeKind.Local).AddTicks(7211),
                            DOB = new DateTime(2003, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "srinivasan@zucisystems.com",
                            IsActive = true,
                            Name = "Srinivasan Arumugam",
                            PhoneNumber = "1234567890",
                            Role = "Developer",
                            UpdatedOn = new DateTime(2025, 8, 7, 19, 52, 55, 891, DateTimeKind.Local).AddTicks(7213)
                        });
                });

            modelBuilder.Entity("EmployeeLibrary.Models.Employee", b =>
                {
                    b.HasOne("EmployeeLibrary.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EmployeeLibrary.Models.Company", null)
                        .WithMany("Employees")
                        .HasForeignKey("CompanyId1");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("EmployeeLibrary.Models.Company", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
