// <auto-generated />
using System;
using EmployeeLibrary;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeLibrary.Migrations
{
    [DbContext(typeof(EmployeeDbContext))]
    [Migration("20250811130448_Migration_V2")]
    partial class Migration_V2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeeLibrary.Models.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e2780185-d9ee-4067-958f-30565ae77673"),
                            Address = "123 Main St, Thoraipakkam, Chennai",
                            CreatedOn = new DateTime(2025, 8, 11, 18, 34, 47, 469, DateTimeKind.Local).AddTicks(8313),
                            Description = "Zuci Systems is a leading software development company specializing in custom software solutions, mobile app development, and web application development. We are committed to delivering high-quality software products that meet the unique needs of our clients.",
                            Email = "zucisystems@zucisystems.com",
                            IsActive = true,
                            Name = "Zuci Systems",
                            PhoneNumber = "1234567890",
                            UpdatedOn = new DateTime(2025, 8, 11, 18, 34, 47, 469, DateTimeKind.Local).AddTicks(8342)
                        });
                });

            modelBuilder.Entity("EmployeeLibrary.Models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("95476122-af29-42a3-beaa-e0075b01120f"),
                            Address = "123 Sai Baba PG, Thoraipakkam, Chennai",
                            CompanyId = new Guid("e2780185-d9ee-4067-958f-30565ae77673"),
                            CreatedOn = new DateTime(2025, 8, 11, 18, 34, 47, 469, DateTimeKind.Local).AddTicks(8822),
                            DOB = new DateTime(2003, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "bala@zucisystems.com",
                            IsActive = true,
                            Name = "Bala Venkata Rama Sai Immadisetty",
                            PhoneNumber = "9876543210",
                            Role = "Developer",
                            UpdatedOn = new DateTime(2025, 8, 11, 18, 34, 47, 469, DateTimeKind.Local).AddTicks(8825)
                        },
                        new
                        {
                            Id = new Guid("0ecb31b4-5610-4652-8205-5a05d52bafcb"),
                            Address = "123 Annai Indira Nagar, Thoraipakkam, Chennai",
                            CompanyId = new Guid("e2780185-d9ee-4067-958f-30565ae77673"),
                            CreatedOn = new DateTime(2025, 8, 11, 18, 34, 47, 469, DateTimeKind.Local).AddTicks(8837),
                            DOB = new DateTime(2003, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "srinivasan@zucisystems.com",
                            IsActive = true,
                            Name = "Srinivasan Arumugam",
                            PhoneNumber = "1234567890",
                            Role = "Developer",
                            UpdatedOn = new DateTime(2025, 8, 11, 18, 34, 47, 469, DateTimeKind.Local).AddTicks(8839)
                        });
                });

            modelBuilder.Entity("EmployeeLibrary.Models.Employee", b =>
                {
                    b.HasOne("EmployeeLibrary.Models.Company", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("EmployeeLibrary.Models.Company", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
