// <auto-generated />
using System;
using EmployeeLibrary;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeLibrary.Migrations
{
    [DbContext(typeof(EmployeeDbContext))]
    partial class EmployeeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeeLibrary.Models.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("47569087-1f5b-4702-acb3-91e5643fa27a"),
                            Address = "123 Main St, Thoraipakkam, Chennai",
                            CreatedOn = new DateTime(2025, 9, 2, 12, 12, 48, 316, DateTimeKind.Local).AddTicks(9205),
                            Description = "Zuci Systems is a leading software development company specializing in custom software solutions, mobile app development, and web application development. We are committed to delivering high-quality software products that meet the unique needs of our clients.",
                            Email = "zucisystems@zucisystems.com",
                            IsActive = true,
                            Name = "Zuci Systems",
                            PhoneNumber = "1234567890",
                            UpdatedOn = new DateTime(2025, 9, 2, 12, 12, 48, 316, DateTimeKind.Local).AddTicks(9220)
                        });
                });

            modelBuilder.Entity("EmployeeLibrary.Models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ba336be5-5ea1-45cb-8262-27e1cd0f6074"),
                            Address = "123 Sai Baba PG, Thoraipakkam, Chennai",
                            CompanyId = new Guid("47569087-1f5b-4702-acb3-91e5643fa27a"),
                            CreatedOn = new DateTime(2025, 9, 2, 12, 12, 48, 316, DateTimeKind.Local).AddTicks(9448),
                            DOB = new DateTime(2003, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "bala@zucisystems.com",
                            IsActive = true,
                            Name = "Bala Venkata Rama Sai Immadisetty",
                            PhoneNumber = "9876543210",
                            Role = "Developer",
                            UpdatedOn = new DateTime(2025, 9, 2, 12, 12, 48, 316, DateTimeKind.Local).AddTicks(9450)
                        },
                        new
                        {
                            Id = new Guid("79fea8d2-1c63-480a-9786-a404fa1a1255"),
                            Address = "123 Annai Indira Nagar, Thoraipakkam, Chennai",
                            CompanyId = new Guid("47569087-1f5b-4702-acb3-91e5643fa27a"),
                            CreatedOn = new DateTime(2025, 9, 2, 12, 12, 48, 316, DateTimeKind.Local).AddTicks(9457),
                            DOB = new DateTime(2003, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "srinivasan@zucisystems.com",
                            IsActive = true,
                            Name = "Srinivasan Arumugam",
                            PhoneNumber = "1234567890",
                            Role = "Developer",
                            UpdatedOn = new DateTime(2025, 9, 2, 12, 12, 48, 316, DateTimeKind.Local).AddTicks(9458)
                        });
                });

            modelBuilder.Entity("EmployeeLibrary.Models.Employee", b =>
                {
                    b.HasOne("EmployeeLibrary.Models.Company", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("EmployeeLibrary.Models.Company", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
